# Generated by Django 2.0 on 2020-06-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('unit', models.IntegerField(choices=[(1, 'GRAM'), (2, 'POUND'), (3, 'OUNCE'), (4, 'KG'), (5, 'TON')])),
                ('yield_ph', models.FloatField()),
                ('maturity_time', models.IntegerField()),
                ('storage_condition', models.IntegerField()),
                ('storage_time_unit', models.IntegerField(choices=[(1, 'HOURS'), (2, 'DAYS'), (3, 'MONTHS')])),
                ('storage_time', models.IntegerField()),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.BigIntegerField()),
                ('modified_at', models.BigIntegerField()),
            ],
        ),
    ]
